services:
    nginx-service:
        image: nginx:latest
        container_name: nginx
        restart: unless-stopped
        ports:
            - 80:80
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - git-clone-service
            - db-service-2
            - php-service-8.2
            - admin-panel
            - cache-service
        networks:
            - workspace

    git-clone-service:
        image: alpine:latest
        container_name: git-clone
        command: /bin/sh -c "git clone https://github.com/oddsGold/wiki-admin-panel.git /var/www && chown -R www-data:www-data /var/www"
        volumes:
            - .:/var/www
        networks:
            - workspace

    db-service-2:
        image: mariadb:10.4.8
        container_name: mariadb-10
        ports:
            - 3306:3306
        volumes:
            - ./db/mariadb/data:/var/lib/mysql
            - ./db/mariadb/mariadb.cnf:/etc/mysql/mariadb.cnf:ro
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: unless-stopped
        environment:
            MYSQL_ROOT_HOST: "%"
            MYSQL_ROOT_PASSWORD: password
            MYSQL_PASSWORD: password
            MARIADB_ROOT_PASSWORD: password
        networks:
            - workspace

    php-service-8.2:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: php-fpm-8.2
        restart: unless-stopped
        ports:
            - 9082:9082
        volumes:
            - .:/var/www
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        depends_on:
            - git-clone-service
        networks:
            - workspace
        environment:
            XDEBUG_MODE: debug
            XDEBUG_CONFIG: client_host=host.docker.internal

    admin-panel:
        build:
            context: .
            dockerfile: ./docker/react/Dockerfile.prod
        container_name: admin_panel
        ports:
            - "3001:5173"
        volumes:
            - .:/app
            - /app/node_modules
        environment:
            - CHOKIDAR_USEPOLLING=true
            - HOST=0.0.0.0
        networks:
            - workspace


    cache-service:
        image: redis:latest
        container_name: redis
        restart: unless-stopped
        ports:
            - 6379:6379
        networks:
            - workspace


networks:
    workspace:

