services:
    nginx-service:
        image: nginx:latest
        container_name: nginx
        restart: unless-stopped
        ports:
            - 8080:80
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - db-service-2
            - php-service-8.2
            - admin-panel
            - cache-service
        networks:
            - workspace

    db-service-2:
        image: mariadb:10.4.8
        container_name: mariadb-10
        ports:
            - 3306:3306
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: unless-stopped
        environment:
            MARIADB_ROOT_PASSWORD: root
            MARIADB_DATABASE: wiki
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - dbdata:/var/lib/mysql
            - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - workspace

    php-service-8.2:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=db-service-2
            - DB_PORT=3306
            - DB_DATABASE=wiki
            - DB_USERNAME=root
            - DB_PASSWORD=root
            - APP_ENV=production
            - APP_DEBUG=false
        container_name: php-fpm-8.2
        restart: unless-stopped
        ports:
            - 9082:9082
        volumes:
            - .:/var/www
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        depends_on:
            - db-service-2
        networks:
            - workspace

    admin-panel:
        build:
            context: .
            dockerfile: ./docker/react/Dockerfile
        container_name: admin_panel_wiki
        volumes:
            - .:/var/www
        networks:
            - workspace

    cache-service:
        image: redis:latest
        container_name: redis-wiki
        restart: unless-stopped
        ports:
            - 6379:6379
        networks:
            - workspace

networks:
    workspace:

volumes:
    dbdata:
